version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'maven'
    directory: '/releng/edu.toronto.cs.se.mmint.releng'
    target-branch: 'develop'
    schedule:
      interval: 'daily'

