language: java
jdk:
 - oraclejdk8
cache:
 directories:
  - $HOME/.m2
before_install:
 - echo -e "Host cs.toronto.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
 - openssl aes-256-cbc -K $encrypted_631ea21ad1d0_key -iv $encrypted_631ea21ad1d0_iv -in releng/deploy_key.enc -out releng/deploy_key -d
script:
 - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
 - mvn -f releng/edu.toronto.cs.se.modelepedia.libz3java.releng/pom.xml clean install
 - mvn -f releng/edu.toronto.cs.se.mmint.releng/pom.xml clean install
after_success:
 - chmod 600 releng/deploy_key
 - mv releng/deploy_key ~/.ssh/id_rsa
 - if [ $TRAVIS_BRANCH = master ]; then DIR=release; DIR=$TRAVIS_BRANCH; fi
 - ssh adisandro@cs.toronto.edu 'rm -rf ~/public_html/mmint/$DIR/'
 - rsync -r releng/edu.toronto.cs.se.mmint.install/target/repository/ adisandro@cs.toronto.edu:~/public_html/mmint/$DIR/
