language: java
jdk:
 - oraclejdk8
cache:
 directories:
  - $HOME/.m2
script:
 - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
 - cd releng/edu.toronto.cs.se.modelepedia.libz3java.releng
 - mvn clean install
 - cd ../edu.toronto.cs.se.mmint.releng
 - mvn clean install
