language: java
jdk:
 - oraclejdk8
addons:
 apt:
  packages:
   - oracle-java8-installer
cache:
 directories:
  - $HOME/.m2
before_install:
 - test $TRAVIS_PULL_REQUEST = false \
   && echo "Host cs.toronto.edu StrictHostKeyChecking no" >> ~/.ssh/config \
   && openssl aes-256-cbc -K $encrypted_631ea21ad1d0_key -iv $encrypted_631ea21ad1d0_iv -in releng/deploy_key.enc -out releng/deploy_key -d
script:
 - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
 - mvn -f releng/edu.toronto.cs.se.modelepedia.libz3java.releng/pom.xml clean install
 - mvn -f releng/edu.toronto.cs.se.mmint.releng/pom.xml clean install
after_success:
 - test $TRAVIS_PULL_REQUEST = false \
   && chmod 600 releng/deploy_key \
   && mv releng/deploy_key ~/.ssh/id_rsa \
   && ssh adisandro@cs.toronto.edu "rm -rf ~/public_html/mmint/${TRAVIS_BRANCH/master/release}/" \
   && rsync -r releng/edu.toronto.cs.se.mmint.install/target/repository/ adisandro@cs.toronto.edu:~/public_html/mmint/${TRAVIS_BRANCH/master/release}/
