name: Build and Deploy
on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout MMINT
        uses: actions/checkout@v2.3.4

      - name: Install Java 15
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '16-ea'

      - name: Load Maven cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ hashFiles('releng/edu.toronto.cs.se.mmint.releng/pom.xml') }}
          restore-keys: ${{ runner.os }}-

      - name: Build Libz3java
        run: mvn -T 1C -f releng/edu.toronto.cs.se.modelepedia.libz3java.releng/pom.xml clean install

      - name: Build MMINT
        run: mvn -T 1C -f releng/edu.toronto.cs.se.mmint.releng/pom.xml clean install

      - name: Checkout update site
        if: github.event_name == 'push'
        uses: actions/checkout@v2.3.4
        with:
          repository: adisandro/adisandro.github.io
          path: deploy
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Deploy
        if: github.event_name == 'push'
        env:
          BRANCH: ${{ github.ref }}
        run: |
          BRANCH=${BRANCH##*/}
          cd deploy
          rm -rf mmint/${BRANCH/main/release}
          mv ../releng/edu.toronto.cs.se.mmint.install/target/repository mmint/${BRANCH/main/release}
          git config user.name "Deploy CI Bot"
          git config user.email "deploy@github.com"
          git add .
          git reset --soft HEAD~1
          git commit -m "mmint: Deploy build"
          git push -f

