name: Build and Deploy
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout MMINT
        uses: actions/checkout@v4

      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Maven 3.9.5
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5

      - name: Load Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ hashFiles('releng/edu.toronto.cs.se.mmint.releng/pom.xml') }}

      - name: Build MMINT
        run: mvn -f releng/edu.toronto.cs.se.mmint.releng/pom.xml clean install

      - name: Checkout update site
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: adisandro/adisandro.github.io
          path: deploy
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Deploy
        if: github.event_name == 'push'
        env:
          BRANCH: ${{ github.ref }}
        run: |
          BRANCH=${BRANCH##*/}
          cd deploy
          rm -rf mmint/${BRANCH/main/release}
          mv ../releng/edu.toronto.cs.se.mmint.install/target/repository mmint/${BRANCH/main/release}
          git config user.name "Deploy CI Bot"
          git config user.email "deploy@github.com"
          git add .
          git reset --soft HEAD~1
          git commit -m "mmint: Deploy build"
          git push -f

