name: Build and Deploy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout MMINT repo
        uses: actions/checkout@v2.3.4

      - name: Install Java 15
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '15'

      - name: Load cache of Maven dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ hashFiles('releng/edu.toronto.cs.se.mmint.releng/pom.xml') }}
          restore-keys: ${{ runner.os }}-

      - name: Build Libz3java
        run: mvn -T 1C -f releng/edu.toronto.cs.se.modelepedia.libz3java.releng/pom.xml clean install

      - name: Build MMINT
        run: mvn -T 1C -f releng/edu.toronto.cs.se.mmint.releng/pom.xml clean install

      - name: Store binary jars
        uses: actions/upload-artifact@v2.2.1
        with:
          name: UpdateSite
          path: releng/edu.toronto.cs.se.mmint.install/target/repository

      - name: Prepare deployment
        if: github.event_name == 'push'
        uses: actions/checkout@v2.3.4
        with:
          repository: adisandro/adisandro.github.io
          path: deploy
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Deploy
        if: github.event_name == 'push'
        env:
          BRANCH: ${{ github.ref }}
        run: |
          BRANCH=${BRANCH##*/}
          cd deploy
          rm -rf mmint/${BRANCH/master/release}
          mv ../releng/edu.toronto.cs.se.mmint.install/target/repository mmint/${BRANCH/master/release}
          git add .
          git reset --soft HEAD~1
          git commit --author="Alessio Di Sandro <alessio.disandro@gmail.com>" -m "mmint: Update build"
          git push -f

